### ISSUE TITLE
worker id reservation security

### ISSUE THREAD

**Issue by rlcee** [fermitools/data_dispatcher#18]
Can worker_1 reserve a file and then worker_2 declare it done?  If so, can we enforce only the worker_id with the reservation can declare a file done or failed?  This important to prevent a rogue job from interrupting a known good job with the current reservation.  I believe this reservation ownership check is fundamental to the idea of "reserve".

**Comment by marcmengel** [comment]
Hm... The problem is, currently the 'release' call that the client makes for file_done() and file_failed()  doesn't  even take the
worker_id as a parameter, so that we could check it.   So if we require being passed a worker-id that matches the
reservation, current clients would simply fail.     We could implement a middle ground, where *if* you pass in a a worker_id, we require it to match the reservation; [ then newer clients would have this check, but older ones wouldn't;] then some time from now when we've updated clients everywhere, we could make it mandatory...

**Comment by marcmengel** [comment]
I put an update for this on the reservation_security branch;  It still needs a test to validate it, and to be tested...
